# Generated by Django 4.2.6 on 2024-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(max_length=200, verbose_name='Соединение'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(max_length=200, verbose_name='Другие названия'),
        ),
    ]
